-- Centros de acopio adicionales en Lara
-- Ejecutar en Supabase SQL Editor si ya tienes las tablas creadas.

INSERT INTO help_centers (
  name,
  description,
  type,
  state,
  city,
  address,
  latitude,
  longitude,
  phone,
  schedule,
  accepts,
  is_verified,
  is_active
)
VALUES
  (
    'Defensa Animal Venezuela — Barquicenter',
    'Centro de acopio en Barquisimeto coordinado por Defensa Animal Venezuela para recibir insumos de apoyo durante la emergencia.',
    'ngo',
    'Lara',
    'Barquisimeto',
    'Av. 20, entre calles 22 y 23, C.C. Barquicenter, nivel sótano, El Centro',
    10.0677583,
    -69.3136004,
    NULL,
    'Por confirmar',
    ARRAY['water', 'food', 'medicine', 'hygiene', 'blankets'],
    true,
    true
  ),
  (
    'Estación de Bomberos de Palavecino',
    'Centro de acopio y punto de apoyo de emergencia en Cabudare, municipio Palavecino.',
    'government',
    'Lara',
    'Cabudare',
    'Los Rastrojos, calle paralela a la Av. Intercomunal, Cabudare',
    10.0238255,
    -69.245363,
    '0251-2614536',
    '24 horas',
    ARRAY['water', 'food', 'medicine', 'clothing', 'hygiene', 'blankets'],
    true,
    true
  ),
  (
    'Decanato de Ciencias de la Salud — UCLA',
    'Centro de acopio habilitado en el Decanato de Ciencias de la Salud Dr. Pablo Acosta Ortiz de la UCLA.',
    'university',
    'Lara',
    'Barquisimeto',
    'Av. Libertador con Av. Andrés Bello, al lado del Hospital Central Universitario Dr. Antonio María Pineda',
    10.0818213,
    -69.3110486,
    '0251-2591919',
    'Por confirmar',
    ARRAY['water', 'food', 'medicine', 'clothing', 'hygiene', 'blankets'],
    true,
    true
  ),
  (
    'Pa'' Todo — La Pasarela',
    'Centro de acopio habilitado en el Pa'' Todo de La Pasarela para recibir insumos durante la emergencia.',
    'community',
    'Lara',
    'Barquisimeto',
    'Av. Libertador, sector La Pasarela, frente a la pasarela peatonal (referencia: calle 33)',
    10.0803,
    -69.3223,
    NULL,
    'Por confirmar',
    ARRAY['water', 'food', 'medicine', 'clothing', 'hygiene', 'blankets'],
    true,
    true
  ),
  (
    'La Flor de Venezuela — Camión de acopio',
    'Camión habilitado como centro de acopio en las inmediaciones de La Flor de Venezuela para recibir insumos durante la emergencia.',
    'community',
    'Lara',
    'Barquisimeto',
    'La Flor de Venezuela, Av. Venezuela con Av. Argimiro Bracamonte, Triángulo del Este',
    10.0724026,
    -69.2897697,
    NULL,
    'Por confirmar',
    ARRAY['water', 'food', 'medicine', 'clothing', 'hygiene', 'blankets'],
    true,
    true
  ),
  (
    'Zona Saludable Training Center',
    'Centro de acopio que recibe donaciones para los afectados. El camión con las donaciones sale el sábado hacia Caracas.',
    'community',
    'Lara',
    'Barquisimeto',
    'Av. Rotaria, Carrera 14B, entre calle 62 y Av. Rotaria',
    10.0570081,
    -69.3547332,
    NULL,
    '6:00 AM - 8:00 PM (camión sale el sábado hacia Caracas)',
    ARRAY['water', 'food', 'medicine', 'hygiene', 'clothing', 'blankets'],
    true,
    true
  ),
  (
    'HOSPITOUR — Centro de Acopio',
    'Recaudando donaciones para familias afectadas por el terremoto. También acepta pañales, sábanas, almohadas y calzado. Instagram: @hospitourvzla',
    'ngo',
    'Lara',
    'Barquisimeto',
    'Carrera 25, entre calles 14 y 15, Barquisimeto',
    10.0720528,
    -69.3148163,
    '0424-5541012',
    'Por confirmar',
    ARRAY['water', 'food', 'medicine', 'hygiene', 'clothing', 'blankets'],
    true,
    true
  ),
  (
    'Consultorio VetLife — Centro de Acopio para Mascotas',
    'Centro de acopio para mascotas lesionadas durante el terremoto (Dra. Luissimar Aguilar, Centro Diagnóstico de Especialidades Veterinarias). Reciben: alimentos concentrados secos o húmedos, agua potable, mantas, correas y collares de identificación. Fármacos: analgésicos (Meloxicam, Dipirona, Caprofeno, Firocoxib, Metadol), antiinflamatorios esteroideos, cremas cicatrizantes y solución de cloruro de sodio 0,9%. Insumos: gasas, jeringas, adhesivos, macro y microgoteros, pericraneales y catéteres intravenosos (20G, 22G, 24G, 26G). Lo recaudado será destinado a un centro de acopio masivo.',
    'ngo',
    'Lara',
    'Barquisimeto',
    'Av. Morán, entre Av. Venezuela y Carrera 26A, Barquisimeto',
    10.0608,
    -69.301,
    NULL,
    'Por confirmar',
    ARRAY['water', 'food', 'medicine', 'blankets'],
    true,
    true
  );
